# This file is generated by packaging/render_release.py — DO NOT EDIT BY HAND.
# Source template: packaging/homebrew/symbiote.rb.tmpl
class Symbiote < Formula
  desc "Terminal client for the Symbiote Orchestrator platform"
  homepage "https://github.com/symbiote-labs/symbiote-cli-dist"
  version "1.2.0"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.2.0/symbiote-1.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "97d8c9eb34470f30f1a13b23d5fa2cabcab7a75a6d3f3d53ce892b0483e97ec0"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.2.0/symbiote-1.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "8745ce853f3591d1fd1e7fa1e1c8a9d76bcdf6320d1a9c41dd872b90910cc8dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.2.0/symbiote-1.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1a30d7b263710f925210292b4c20e653b1fbdcc33342a6ec3524d54c2a113814"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.2.0/symbiote-1.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "04f9f4e728ae3ee4c58925d8ac90c06e1d2afe26f6cfb34040ba66b4601ffa12"
    end
  end

  def install
    # PyInstaller --onedir tree: the launcher plus its _internal/ payload.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"symbiote"
  end

  test do
    assert_match "symbiote #{version}", shell_output("#{bin}/symbiote version")
  end
end
