# This file is generated by packaging/render_release.py — DO NOT EDIT BY HAND.
# Source template: packaging/homebrew/symbiote.rb.tmpl
class Symbiote < Formula
  desc "Terminal client for the Symbiote Orchestrator platform"
  homepage "https://github.com/symbiote-labs/symbiote-cli-dist"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.0/symbiote-1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "aeba7a07abc48e088de5652823b3cfa56de34015ed4562527019c1a44df41f9b"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.0/symbiote-1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "392aa8478383cbcdc8f73de36b366564cc5c8b29fda84480a0fa6509cea620a1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.0/symbiote-1.0.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f8e8b90d291351aa3a7b0cea6413618ccd048d32766d9663b9df5c8c05982710"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.0/symbiote-1.0.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7f9793f579ffd40ce75ba1f824291ae3a873c10cac4af991fd9a62d792fe33f6"
    end
  end

  def install
    # PyInstaller --onedir tree: the launcher plus its _internal/ payload.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"symbiote"
  end

  test do
    assert_match "symbiote #{version}", shell_output("#{bin}/symbiote version")
  end
end
