# This file is generated by packaging/render_release.py — DO NOT EDIT BY HAND.
# Source template: packaging/homebrew/symbiote.rb.tmpl
class Symbiote < Formula
  desc "Terminal client for the Symbiote Orchestrator platform"
  homepage "https://github.com/symbiote-labs/symbiote-cli-dist"
  version "1.0.1"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.1/symbiote-1.0.1-aarch64-apple-darwin.tar.gz"
      sha256 "cfb52dbaec22c38bdff3f6f296fba68a8504e10d61e062e6ce896748888b9c9e"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.1/symbiote-1.0.1-x86_64-apple-darwin.tar.gz"
      sha256 "5e69dfbcf25135207a70f104ac76049759d8f06a641a03aeb6928b33fed8b866"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.1/symbiote-1.0.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "370b4cca2e3033fb8e8082c9b7f4ffddaaba9b8ae01c30c5b5d1fd5f260e064d"
    end
    on_intel do
      url "https://github.com/symbiote-labs/symbiote-cli-dist/releases/download/cli-v1.0.1/symbiote-1.0.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9fe3e1cf5974334d45a3fdccebb7c7bfca1c19acf72d6c6447cd8fe8b72c1fa6"
    end
  end

  def install
    # PyInstaller --onedir tree: the launcher plus its _internal/ payload.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"symbiote"
  end

  test do
    assert_match "symbiote #{version}", shell_output("#{bin}/symbiote version")
  end
end
